"""Deploy keys, and the GitHub environment they are published to.

This is a sixth concern rather than a step in ``tools``: nothing here renders a
template or drives OpenTofu or Ansible, and the credentials it moves belong to a
service outside the stack entirely.

Every repository named in desired state gets one keypair on every create. The
public half is installed on the box behind a ForceCommand restricted to the
hosts that repository serves, and the private half is published to a GitHub
Actions environment named after the profile. Nothing is stored: the keys are
regenerated next create, which is affordable because the ForceCommand means a
leaked key can trigger a redeploy of that repository's own applications and
nothing else.

The repository is the unit rather than the application because that is where the
key is stored and what triggers its use. One image answering for several hosts is
still one pipeline, and keying per application would publish two keys into one
environment, where the second overwrites the first.

Keys are generated by ``ssh-keygen`` rather than in process. Three languages
agreeing on OpenSSH private-key encoding is a parity problem; one subprocess is
not.

The private key is never passed as an argument. The runtime seam spawns with
stdin on DEVNULL, so it cannot be piped either — instead the key stays in the
0600 file ``ssh-keygen`` wrote and ``gh`` reads it through a shell redirect, so
it stays out of the process table the same way stdin would have kept it.
"""

from __future__ import annotations

import shutil
import tempfile
from pathlib import Path
from typing import Awaitable, Callable

from blue.process import run_plan
from blue.runtime import ExecResult, runtime

from .access import identity_args, register_cleanup
from .validate import deploy_groups

_RUN_TIMEOUT_MS = 30_000

Runner = Callable[..., Awaitable[ExecResult]]

# The public key a build renders. Generation is a create-time side effect, so
# build and dry-run need a value that never changes — a fresh key every build
# would make the rendered artifact nondeterministic and break byte parity.
_PLACEHOLDER_PUBLIC = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBUILDPLACEHOLDER0000000000000000000000"


async def _default_runner(args: list[str], *, env: dict | None = None) -> ExecResult:
    return await runtime.exec(args, env=env, timeout_ms=_RUN_TIMEOUT_MS)


def key_comment(opts: dict, github: str) -> str:
    """Identify a key on the box, and the value retention groups generations by.

    Carries no timestamp: the comment is rendered into the artifact, and a clock
    reading there would break byte parity. Ordering for retention comes from
    position in authorized_keys instead.

    The ``/`` is slugged because this sits in an authorized_keys comment field.
    Nothing parses it back apart — retention compares whole comments, so a
    profile, owner, or repository containing a dash stays unambiguous.
    """
    return f"once-deploy-{opts.get('profile') or 'default'}-{str(github).replace('/', '-')}"


def placeholder_keys(opts: dict) -> list[dict]:
    """What a build or dry-run uses in place of generated keys."""
    return [
        {
            "hosts": group["hosts"],
            "github": group["github"],
            "public": f"{_PLACEHOLDER_PUBLIC} {key_comment(opts, group['github'])}",
        }
        for group in deploy_groups(opts)
    ]


def _keygen_args(opts: dict, github: str, path: str) -> list[str]:
    return ["ssh-keygen", "-t", "ed25519", "-N", "", "-q", "-C", key_comment(opts, github), "-f", path]


async def generate_keys(opts: dict, run_fn: Runner | None = None) -> tuple[list[dict], str | None]:
    """Generate one keypair per repository named in desired state.

    Returns the keys and an error. The keys carry the public half inline and the
    private half only as a path, so the secret never enters the opts map.
    """
    run = run_fn or _default_runner
    groups = deploy_groups(opts)
    if not groups:
        return [], None
    directory = tempfile.mkdtemp(prefix="once-deploy")
    def cleanup():
        shutil.rmtree(directory, ignore_errors=True)
    try:
        register_cleanup(cleanup)
        keys: list[dict] = []
        for index, group in enumerate(groups):
            path = str(Path(directory) / f"key-{index}")
            result = await run(_keygen_args(opts, group["github"], path))
            if result.exit != 0:
                cleanup()
                return [], f"ssh-keygen failed for {group['github']}: {str(result.err or '').strip()}"
            keys.append(
                {
                    "hosts": group["hosts"],
                    "github": group["github"],
                    "public": Path(f"{path}.pub").read_text().strip(),
                    "private-file": path,
                }
            )
        return keys, None
    except BaseException:
        cleanup()
        raise



def public_keys(opts: dict) -> list[dict]:
    """The render-facing view: hosts and public key only.

    ``tools`` builds the authorized_keys lines from this, so no private key can
    reach a template.
    """
    return [{"hosts": key["hosts"], "public": key["public"]} for key in opts.get("once/deploy-keys") or []]


# --------------------------------------------------------------- the gh commands


def _env_name(opts: dict) -> str:
    return str(opts.get("profile") or "default")


def host_key_args(opts: dict) -> list[str]:
    """Read the server's own SSH host key over the administrative connection.

    A workflow can then pin it instead of running ssh-keyscan on every deploy.
    This is still trust on first use — nothing here has a prior binding for that
    key either. What it changes is the window: CI stops asking the network who
    the server is on every single deploy, and starts comparing against a value
    captured once, so a substituted key is detected from then on.
    """
    return [
        "ssh", "-o", "BatchMode=yes", "-o", "ConnectTimeout=10",
        "-o", "StrictHostKeyChecking=accept-new",
        *identity_args(opts),
        f"{opts.get('user') or 'root'}@{opts.get('ip')}",
        "cat /etc/ssh/ssh_host_ed25519_key.pub",
    ]


def known_hosts_line(ip: object, pub: object) -> str | None:
    """A known_hosts entry from an ssh_host_*.pub file's contents.

    The trailing comment is dropped: it is the server's own hostname at key
    generation time and means nothing to a client.
    """
    parts = str(pub or "").strip().split()
    if len(parts) < 2 or not parts[0].startswith("ssh-"):
        return None
    return f"{ip} {parts[0]} {parts[1]}"


async def fetch_host_key(opts: dict, run_fn: Runner) -> str | None:
    """The known_hosts line for this stack's server, or None if unreadable.

    A failure here is not fatal: the credentials are still worth publishing, and
    a workflow that finds no SSH_KNOWN_HOSTS can say so itself.
    """
    result = await run_fn(host_key_args(opts))
    return known_hosts_line(opts.get("ip"), result.out) if result.exit == 0 else None


def _shell_quote(value: object) -> str:
    """Always quote, so the command is byte-identical to the other colours.

    ``shlex.quote`` leaves a string without metacharacters bare, which would
    make Blue emit a different command than Green and Red for the same input.
    """
    inner = str(value).replace("'", "'\\''")
    return f"'{inner}'"


def publish_commands(opts: dict, key: dict) -> list[dict]:
    """The gh invocations that publish one application's credentials.

    Pure, so a test can assert the exact argv without a process.

    The ip and user are variables rather than secrets: DNS already reveals the
    address, and masking them only makes CI logs harder to read.

    The environment is created first, with an idempotent PUT. A workflow that
    names an environment does bring it into being, which would have kept this
    token off admin scope — but that only helps once the workflow has been wired
    to the environment, and nothing here can guarantee that came first. Writing
    into an environment that does not exist is a 404, so ONCE creates it.
    """
    env = _env_name(opts)
    repo = str(key.get("github"))
    base = ["--repo", repo, "--env", env]
    redirect = (
        f"gh secret set SSH_PRIVATE_KEY --repo {_shell_quote(repo)} "
        f"--env {_shell_quote(env)} < {_shell_quote(key.get('private-file'))}"
    )
    return [
        {"label": f"{repo} environment {env}", "args": ["gh", "api", "--method", "PUT", "--silent", f"repos/{repo}/environments/{env}"]},
        {"label": f"{repo} SERVER_IP", "args": ["gh", "variable", "set", "SERVER_IP", *base, "--body", str(opts.get("ip"))]},
        {"label": f"{repo} SERVER_USER", "args": ["gh", "variable", "set", "SERVER_USER", *base, "--body", "deploy"]},
        {"label": f"{repo} SSH_KNOWN_HOSTS", "args": ["gh", "variable", "set", "SSH_KNOWN_HOSTS", *base, "--body", str(opts.get("once/known-hosts") or "")]},
        {"label": f"{repo} SSH_PRIVATE_KEY", "args": ["sh", "-c", redirect]},
    ]


def revoke_commands(opts: dict, key: dict) -> list[dict]:
    """The gh invocations that withdraw one repository's credentials.

    Delete needs no key material, so this works with the box already destroyed —
    which is why it runs before teardown rather than after.
    """
    env = _env_name(opts)
    repo = str(key.get("github"))
    base = ["--repo", repo, "--env", env]
    return [
        {"label": f"{repo} SERVER_IP", "args": ["gh", "variable", "delete", "SERVER_IP", *base]},
        {"label": f"{repo} SERVER_USER", "args": ["gh", "variable", "delete", "SERVER_USER", *base]},
        {"label": f"{repo} SSH_KNOWN_HOSTS", "args": ["gh", "variable", "delete", "SSH_KNOWN_HOSTS", *base]},
        {"label": f"{repo} SSH_PRIVATE_KEY", "args": ["gh", "secret", "delete", "SSH_PRIVATE_KEY", *base]},
    ]


def commands(opts: dict) -> list[dict]:
    """Every gh invocation this run makes, in order."""
    if opts.get("blue/event") == "delete":
        # Groups, not applications: a repository named twice was revoked twice
        # before, issuing the same four calls again.
        return [cmd for group in deploy_groups(opts) for cmd in revoke_commands(opts, group)]
    return [cmd for key in (opts.get("once/deploy-keys") or []) for cmd in publish_commands(opts, key)]


# ------------------------------------------------------------------- the step


def _cleanup(opts: dict) -> dict:
    directory = opts.get("once/key-dir")
    if isinstance(directory, str):
        shutil.rmtree(directory, ignore_errors=True)
    keys = [{k: v for k, v in key.items() if k != "private-file"} for key in opts.get("once/deploy-keys") or []]
    return {**{k: v for k, v in opts.items() if k != "once/key-dir"}, "once/deploy-keys": keys}


async def github_step(opts: dict, run_fn: Runner | None = None) -> dict:
    """Publish on create, revoke on delete, do nothing otherwise.

    ``wire_fn`` runs the same branch for build and create, so the event check
    here is what keeps a build from reaching GitHub; ``side_effecting_steps``
    only covers ``--dry-run``.

    A revoke that fails because there is nothing to revoke is not an error:
    delete has to be re-runnable, and a missing secret is the state it is trying
    to reach.
    """
    event = opts.get("blue/event")
    if event not in ("create", "delete"):
        return opts
    run = run_fn or _default_runner
    is_delete = event == "delete"
    if not is_delete and deploy_groups(opts):
        opts = {**opts, "once/known-hosts": await fetch_host_key(opts, run)}
    env = {"GH_TOKEN": str(opts.get("github-token") or "")}
    result = await run_plan(
        commands(opts), runner=lambda command: run(command["args"], env=env),
        continue_on_error=lambda _command, _result: is_delete,
    )
    cleaned = _cleanup(opts)
    if result["exit"]:
        return {**cleaned, "blue/exit": 1, "blue/err": f"gh failed for {result['command']['label']}: {str(result['err'] or '').strip()}"}
    return {**cleaned, "blue/exit": 0}
