#!/usr/bin/env bash
set -euo pipefail

root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

# One fixture, three colours. Feeding the same colors.yml to all of them is
# the point: three files describing "the same" desired state could drift apart
# and quietly weaken every comparison below.
state="$root/test/parity/colors.yml"

build_variant() {
  local variant=$1
  shift
  (
    cd "$root/green"
    env COLORS_PAR_WORKDIR="$tmp/$variant/green" "$@" bb green build -f "$state" >/dev/null
  )
  (
    cd "$root/red"
    env COLORS_PAR_WORKDIR="$tmp/$variant/red" "$@" ./red build -f "$state" >/dev/null
  )
  (
    cd "$root/blue"
    env COLORS_PAR_WORKDIR="$tmp/$variant/blue" "$@" uv run python -m package_once_blue build -f "$state" >/dev/null
  )
  diff -qr "$tmp/$variant/green/parity" "$tmp/$variant/red/parity"
  diff -qr "$tmp/$variant/green/parity" "$tmp/$variant/blue/parity"
}

for provider in azure aws google digitalocean hcloud vultr yandex oci; do
  build_variant "$provider-external" "COLORS_PAR_PROVIDER_COMPUTE=$provider"
done
build_variant external-identity COLORS_PAR_SSH_PRIVATE_KEY_PATH=/tmp/fixture-identity
build_variant yandex-static COLORS_PAR_PROVIDER_COMPUTE=yandex COLORS_PAR_YANDEX_STATIC_IP=true COLORS_PAR_YANDEX_ALLOW_STOPPING_FOR_UPDATE=true
build_variant yandex-pinned COLORS_PAR_PROVIDER_COMPUTE=yandex COLORS_PAR_YANDEX_IMAGE_ID=fd8example
build_variant oci-pinned COLORS_PAR_PROVIDER_COMPUTE=oci COLORS_PAR_OCI_IMAGE_ID=ocid1.image.oc1.eu-frankfurt-1.aaaaaaaaexample
sed '/^.*-ssh-authorized-keys:/d; /^.*-ssh-keys:/d; /^compute-pubkey:/d' "$state" > "$tmp/managed.yml"
state="$tmp/managed.yml"
for provider in azure aws google digitalocean hcloud vultr yandex oci; do
  build_variant "$provider-managed" "COLORS_PAR_PROVIDER_COMPUTE=$provider"
done
build_variant no-infra-smtp COLORS_PAR_PROVIDER_SMTP=no-infra
build_variant no-infra-dns COLORS_PAR_PROVIDER_DNS=no-infra
build_variant yandex-dns COLORS_PAR_PROVIDER_DNS=yandex
build_variant r2 COLORS_PAR_PROVIDER_BACKEND=r2

diff -qr "$root/green/src/resources/io/github/getcolors/once" "$root/red/resources"
diff -qr "$root/green/src/resources/io/github/getcolors/once" "$root/blue/src/package_once_blue/resources"

# The colours read YAML through three different parsers — yamlstar, Bun.YAML
# and PyYAML — so agreeing on the generated bytes is only half the contract.
# They also have to agree on what a scalar *means* before rendering starts.
scalars="$root/test/parity/scalars.yml"
(cd "$root/green" && bb ../scripts/scalars-green.clj "$scalars") >"$tmp/scalars-green"
(cd "$root/red" && bun ../scripts/scalars-red.ts "$scalars") >"$tmp/scalars-red"
(cd "$root/blue" && uv run python ../scripts/scalars-blue.py "$scalars") >"$tmp/scalars-blue"
diff "$tmp/scalars-green" "$tmp/scalars-red"
diff "$tmp/scalars-green" "$tmp/scalars-blue"

# `describe` reaches a live host, so none of its logic shows up in the build
# artifacts diffed above — which is exactly how container matching drifted apart
# once already, fixed in one colour while the other two kept the bug. Resolving a
# fixed container set against a fixed host list is pure, so it can be compared
# here without a server.
containers="$root/test/parity/containers.json"
(cd "$root/green" && bb ../scripts/containers-green.clj "$containers") >"$tmp/containers-green"
(cd "$root/red" && bun ../scripts/containers-red.ts "$containers") >"$tmp/containers-red"
(cd "$root/blue" && uv run python ../scripts/containers-blue.py "$containers") >"$tmp/containers-blue"
diff "$tmp/containers-green" "$tmp/containers-red"
diff "$tmp/containers-green" "$tmp/containers-blue"

# The SSH Keypair Standard's create matrix, provider preflight, and delete
# cleanup never reach a build artifact — they run only on real events — and
# their refusal messages are user-facing contract. Each colour drives the same
# scenarios with injected state, keygen, and account-key functions and prints
# normalized outcome lines.
(cd "$root/green" && bb ../scripts/ssh-green.clj) >"$tmp/ssh-green"
(cd "$root/red" && bun ../scripts/ssh-red.ts) >"$tmp/ssh-red"
(cd "$root/blue" && uv run python ../scripts/ssh-blue.py) >"$tmp/ssh-blue"
diff "$tmp/ssh-green" "$tmp/ssh-red"
diff "$tmp/ssh-green" "$tmp/ssh-blue"

# The Compute Provider Standard's operations — selection, the network
# contract, the name rules, the switch and legacy refusals, the state read and
# adoption — are library surface every delegating package calls, and none of
# them reach a build artifact. Each colour drives the same scenarios over one
# two-provider stub spec and prints normalized outcome lines, so a message or
# a rule that drifts in one colour shows up here rather than in a package.
(cd "$root/green" && bb ../scripts/compute-green.clj) >"$tmp/compute-green"
(cd "$root/red" && bun ../scripts/compute-red.ts) >"$tmp/compute-red"
(cd "$root/blue" && uv run python ../scripts/compute-blue.py) >"$tmp/compute-blue"
diff "$tmp/compute-green" "$tmp/compute-red"
diff "$tmp/compute-green" "$tmp/compute-blue"

# The Compute Cluster Standard's operations — the node set, the fallbacks,
# the four node-error classes, the network modes, the topology checks, the
# cluster adoption and the per-node aliases — are the same kind of library
# surface, driven the same way over one three-provider stub spec.
(cd "$root/green" && bb ../scripts/cluster-green.clj) >"$tmp/cluster-green"
(cd "$root/red" && bun ../scripts/cluster-red.ts) >"$tmp/cluster-red"
(cd "$root/blue" && uv run python ../scripts/cluster-blue.py) >"$tmp/cluster-blue"
diff "$tmp/cluster-green" "$tmp/cluster-red"
diff "$tmp/cluster-green" "$tmp/cluster-blue"

# The launcher contract numbers are one fact in three files: green counts
# from 2, red and blue from 1, so green is always the other two plus 8. A
# bump that lands in two colours and not the third is exactly the drift this
# script exists to catch — blue missed one once and carried the wrong number
# for two releases.
green_contract=$(sed -n 's/^  \([0-9][0-9]*\))$/\1/p' "$root/green/src/clj/io/github/getcolors/once/utils.clj" | tail -1)
red_contract=$(sed -n 's/^export const contract = \([0-9]*\);$/\1/p' "$root/red/src/utils.ts")
blue_contract=$(sed -n 's/^CONTRACT = \([0-9]*\)$/\1/p' "$root/blue/src/package_once_blue/utils.py")
if [ "$green_contract" != "$((red_contract + 8))" ] || [ "$green_contract" != "$((blue_contract + 8))" ]; then
  echo "contract numbers disagree: green $green_contract, red $red_contract (+8 = $((red_contract + 8))), blue $blue_contract (+8 = $((blue_contract + 8)))" >&2
  exit 1
fi

echo "green, red, and blue build artifacts are byte-identical"
echo "green, red, and blue agree on every scalar in the parity corpus"
echo "green, red, and blue resolve every container in the parity corpus alike"
echo "green, red, and blue run the machine-key matrix and preflight alike"
echo "green, red, and blue run the compute provider operations alike"
echo "green, red, and blue run the compute cluster operations alike"

# Recorded inventory adapters are not reached by a build.
(cd "$root/green" && bb ../scripts/machine-green.clj "$root/test/parity/machine.json") > "$tmp/machine-green"
(cd "$root/red" && bun ../scripts/machine-red.ts "$root/test/parity/machine.json") > "$tmp/machine-red"
(cd "$root/blue" && uv run python ../scripts/machine-blue.py "$root/test/parity/machine.json") > "$tmp/machine-blue"
python3 - "$tmp" <<'PYTHON'
import json, pathlib, sys
root=pathlib.Path(sys.argv[1])
values=[json.loads((root/('machine-'+color)).read_text()) for color in ['green','red','blue']]
assert values[0]==values[1]==values[2], 'recorded compute parameters differ'
print('green, red, and blue adapt recorded compute inventory alike')
PYTHON

# Graph ordering is not visible in generated files. Gate each native graph.
bash "$root/scripts/ssh-order-parity.sh"

# Resend records arrive only during create, so ordinary builds cannot cover them.
smtp="$root/test/parity/smtp.json"
(cd "$root/green" && bb ../scripts/smtp-green.clj "$smtp") >"$tmp/smtp-green"
(cd "$root/red" && bun ../scripts/smtp-red.ts "$smtp") >"$tmp/smtp-red"
(cd "$root/blue" && uv run python ../scripts/smtp-blue.py "$smtp") >"$tmp/smtp-blue"
diff "$tmp/smtp-green" "$tmp/smtp-red"
diff "$tmp/smtp-green" "$tmp/smtp-blue"
python3 - "$tmp/smtp-green" <<'PYTHON'
import json, sys
records = json.load(open(sys.argv[1]))["resource"]["cloudflare_dns_record"]
by_type = {r["type"]: r for r in records.values()}
assert by_type["CNAME"]["content"] == "send.forge.rmta.net"
assert by_type["CNAME"]["proxied"] is False
assert by_type["CNAME"]["ttl"] == "1"
assert "priority" not in by_type["CNAME"]
assert by_type["MX"]["priority"] == 10
assert by_type["MX"]["content"] == "feedback-smtp.eu-west-1.amazonses.com"
assert by_type["TXT"]["content"] == '\"v=spf1 include:amazonses.com ~all\"'
print("green, red, and blue preserve Resend CNAME targets, MX priorities and TXT quoting")
PYTHON
