#!/usr/bin/env bash
set -euo pipefail

root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

# One fixture, three colours. Feeding the same colors.yml to all of them is
# the point: three files describing "the same" desired state could drift apart
# and quietly weaken every comparison below.
state="$root/test/parity/colors.yml"

build_variant() {
  local variant=$1
  shift
  (
    cd "$root/green"
    env COLORS_PAR_WORKDIR="$tmp/$variant/green" "$@" bb green build -f "$state" >/dev/null
  )
  (
    cd "$root/red"
    env COLORS_PAR_WORKDIR="$tmp/$variant/red" "$@" ./red build -f "$state" >/dev/null
  )
  (
    cd "$root/blue"
    env COLORS_PAR_WORKDIR="$tmp/$variant/blue" "$@" uv run python -m package_once_blue build -f "$state" >/dev/null
  )
  diff -qr "$tmp/$variant/green/parity" "$tmp/$variant/red/parity"
  diff -qr "$tmp/$variant/green/parity" "$tmp/$variant/blue/parity"
}

build_variant local
build_variant azure COLORS_PAR_PROVIDER_COMPUTE=azure
build_variant aws COLORS_PAR_PROVIDER_COMPUTE=aws
build_variant google COLORS_PAR_PROVIDER_COMPUTE=google
build_variant digitalocean-vpc COLORS_PAR_DIGITALOCEAN_VPC_UUID=vpc-123
build_variant hcloud COLORS_PAR_PROVIDER_COMPUTE=hcloud
build_variant yandex COLORS_PAR_PROVIDER_COMPUTE=yandex
# Both toggles of the reserved-address branch. The fixture carries the keys as
# booleans so these overrides are coerced to boolean true — the three template
# engines agree on boolean truthiness, not on the string "false".
build_variant yandex-static COLORS_PAR_PROVIDER_COMPUTE=yandex \
  COLORS_PAR_YANDEX_STATIC_IP=true \
  COLORS_PAR_YANDEX_ALLOW_STOPPING_FOR_UPDATE=true
build_variant oci COLORS_PAR_PROVIDER_COMPUTE=oci
# Both sides of the oci-image-id branch. The unpinned side renders a data
# source and the pinned side renders none, so a colour whose template engine
# handles <% else %> differently diverges here rather than in production.
build_variant oci-pinned COLORS_PAR_PROVIDER_COMPUTE=oci \
  COLORS_PAR_OCI_IMAGE_ID=ocid1.image.oc1.eu-frankfurt-1.aaaaaaaaexample
build_variant no-infra-compute COLORS_PAR_PROVIDER_COMPUTE=no-infra
build_variant no-infra-smtp COLORS_PAR_PROVIDER_SMTP=no-infra
build_variant no-infra-dns COLORS_PAR_PROVIDER_DNS=no-infra
build_variant s3 COLORS_PAR_PROVIDER_BACKEND=s3
build_variant r2 COLORS_PAR_PROVIDER_BACKEND=r2

diff -qr "$root/green/src/resources/io/github/getcolors/once" "$root/red/resources"
diff -qr "$root/green/src/resources/io/github/getcolors/once" "$root/blue/src/package_once_blue/resources"

# The colours read YAML through three different parsers — yamlstar, Bun.YAML
# and PyYAML — so agreeing on the generated bytes is only half the contract.
# They also have to agree on what a scalar *means* before rendering starts.
scalars="$root/test/parity/scalars.yml"
(cd "$root/green" && bb ../scripts/scalars-green.clj "$scalars") >"$tmp/scalars-green"
(cd "$root/red" && bun ../scripts/scalars-red.ts "$scalars") >"$tmp/scalars-red"
(cd "$root/blue" && uv run python ../scripts/scalars-blue.py "$scalars") >"$tmp/scalars-blue"
diff "$tmp/scalars-green" "$tmp/scalars-red"
diff "$tmp/scalars-green" "$tmp/scalars-blue"

# `describe` reaches a live host, so none of its logic shows up in the build
# artifacts diffed above — which is exactly how container matching drifted apart
# once already, fixed in one colour while the other two kept the bug. Resolving a
# fixed container set against a fixed host list is pure, so it can be compared
# here without a server.
containers="$root/test/parity/containers.json"
(cd "$root/green" && bb ../scripts/containers-green.clj "$containers") >"$tmp/containers-green"
(cd "$root/red" && bun ../scripts/containers-red.ts "$containers") >"$tmp/containers-red"
(cd "$root/blue" && uv run python ../scripts/containers-blue.py "$containers") >"$tmp/containers-blue"
diff "$tmp/containers-green" "$tmp/containers-red"
diff "$tmp/containers-green" "$tmp/containers-blue"

echo "green, red, and blue build artifacts are byte-identical"
echo "green, red, and blue agree on every scalar in the parity corpus"
echo "green, red, and blue resolve every container in the parity corpus alike"
