(ns io.github.getcolors.once.github
  "Deploy keys, and the GitHub environment they are published to.

  This is a sixth concern rather than a step in `tools`: nothing here renders a
  template or drives OpenTofu or Ansible, and the credentials it moves belong
  to a service outside the stack entirely.

  Every repository named in desired state gets one keypair on every create. The
  public half is installed on the box behind a ForceCommand restricted to the
  hosts that repository serves, and the private half is published to a GitHub
  Actions environment named after the profile. Nothing is stored: the keys are
  regenerated next create, which is affordable because the ForceCommand means a
  leaked key can trigger a redeploy of that repository's own applications and
  nothing else.

  The repository is the unit rather than the application because that is where
  the key is stored and what triggers its use. One image answering for several
  hosts is still one pipeline, and keying per application would publish two
  keys into one environment, where the second overwrites the first.

  Keys are generated by `ssh-keygen` rather than in process. Three languages
  agreeing on OpenSSH private-key encoding is a parity problem; one subprocess
  is not.

  The private key is never passed as an argument. `green.process` closes a
  child's stdin, so it cannot be piped either — instead the key stays in the
  0600 file `ssh-keygen` wrote and `gh` reads it through a shell redirect, so
  it stays out of the process table the same way stdin would have kept it."
  (:require
   [clojure.java.io :as io]
   [clojure.string :as str]
   [green.process :as process]
   [io.github.getcolors.once.access :as access]
   [io.github.getcolors.once.validate :as validate]))

(def ^:private run-timeout-ms 30000)

(def ^:private placeholder-public
  "The public key a build renders. Generation is a create-time side effect, so
  build and dry-run need a value that never changes — a fresh key every build
  would make the rendered artifact nondeterministic and break byte parity."
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBUILDPLACEHOLDER0000000000000000000000")

(defn key-comment
  "Identifies a key on the box, and the value `files/authorized-keys` groups
  generations by. Carries no timestamp: the comment is rendered into the
  artifact, and a clock reading there would break byte parity. Ordering for
  retention comes from position in authorized_keys instead.

  The `/` is slugged because this sits in an authorized_keys comment field.
  Nothing parses it back apart — retention compares whole comments, so a
  profile, owner, or repository containing a dash stays unambiguous."
  [opts github]
  (format "once-deploy-%s-%s"
          (or (:profile opts) "default")
          (str/replace (str github) "/" "-")))

(defn placeholder-keys
  "What a build or dry-run uses in place of generated keys."
  [opts]
  (mapv (fn [{:keys [github hosts]}]
          {:hosts hosts
           :github github
           :public (str placeholder-public " " (key-comment opts github))})
        (validate/deploy-groups opts)))

(defn- keygen-args
  [opts github path]
  ["ssh-keygen" "-t" "ed25519" "-N" "" "-q"
   "-C" (key-comment opts github)
   "-f" path])

(defn- remove-key-directory! [dir]
  (when (.exists (io/file dir))
    (doseq [file (reverse (file-seq (io/file dir)))]
      (java.nio.file.Files/deleteIfExists (.toPath file)))))

(defn generate-keys
  "Generate temporary application deployment keys. Scope cleanup is registered
  before key generation, covering every later workflow exit. Direct callers
  retain successful keys for publication but generation failures clean up."
  ([opts] (generate-keys opts process/run-with-timeout))
  ([opts run-fn]
   (let [groups (validate/deploy-groups opts)]
     (if (empty? groups)
       [[] nil]
       (let [dir (str (java.nio.file.Files/createTempDirectory
                       "once-deploy"
                       (into-array java.nio.file.attribute.FileAttribute [])))
             cleanup #(remove-key-directory! dir)]
         (try
           (when access/*register!* (access/*register!* :resource cleanup))
           (let [result
                 (loop [[group & more] groups idx 0 acc []]
                   (if-not group
                     [acc nil]
                     (let [path (str (io/file dir (str "key-" idx)))
                           result (run-fn (keygen-args opts (:github group) path) {} run-timeout-ms)]
                       (if-not (zero? (:exit result -1))
                         [nil (format "ssh-keygen failed for %s: %s"
                                      (:github group) (str/trim (str (:err result))))]
                         (recur more (inc idx)
                                (conj acc {:hosts (:hosts group)
                                           :github (:github group)
                                           :public (str/trim (slurp (str path ".pub")))
                                           :private-file path}))))))]
             (when (second result) (cleanup))
             result)
           (catch Throwable error
             (try (cleanup) (catch Throwable cleanup-error (.addSuppressed error cleanup-error)))
             (throw error))))))))

(defn public-keys
  "The render-facing view: hosts and public key only. `tools` builds the
  authorized_keys lines from this, so no private key can reach a template."
  [opts]
  (mapv #(select-keys % [:hosts :public])
        (or (:once/deploy-keys opts) [])))

;;; --------------------------------------------------------------- gh commands

(defn- env-name
  [opts]
  (or (:profile opts) "default"))

(defn- shell-quote
  [s]
  (str "'" (str/replace (str s) "'" "'\\''") "'"))

(defn host-key-args
  "Read the server's own SSH host key over the administrative connection, so a
  workflow can pin it instead of running ssh-keyscan on every deploy.

  This is still trust on first use — nothing here has a prior binding for that
  key either. What it changes is the window: CI stops asking the network who
  the server is on every single deploy, and starts comparing against a value
  captured once, so a substituted key is detected from then on.

  Reading the file over an authenticated session rather than scanning for it
  keeps the answer to one round trip and gets the key type without guessing."
  [opts]
  (-> ["ssh" "-o" "BatchMode=yes" "-o" "ConnectTimeout=10"
       "-o" "StrictHostKeyChecking=accept-new"]
      (into (access/identity-args opts))
      (conj (str (or (:user opts) "root") "@" (:ip opts))
            "cat /etc/ssh/ssh_host_ed25519_key.pub")))

(defn known-hosts-line
  "A known_hosts entry for `ip` from an `ssh_host_*.pub` file's contents. The
  trailing comment is dropped: it is the server's own hostname at key
  generation time and means nothing to a client."
  [ip pub]
  (let [[algo body] (str/split (str/trim (str pub)) #"\s+")]
    (when (and algo body (str/starts-with? algo "ssh-"))
      (format "%s %s %s" ip algo body))))

(defn fetch-host-key
  "The known_hosts line for this stack's server, or nil when it cannot be read.

  A failure here is not fatal: the credentials are still worth publishing, and
  a workflow that finds no SSH_KNOWN_HOSTS can say so itself."
  [opts run-fn]
  (let [result (run-fn (host-key-args opts) {} run-timeout-ms)]
    (when (zero? (:exit result -1))
      (known-hosts-line (:ip opts) (:out result)))))

(defn publish-commands
  "The gh invocations that publish one application's credentials. Pure, so a
  test can assert the exact argv sequence without a process.

  The ip and user are variables rather than secrets: DNS already reveals the
  address, and masking them only makes CI logs harder to read.

  The environment is created first, with an idempotent PUT. A workflow that
  names an environment does bring it into being, which would have kept this
  token off admin scope — but that only helps once the workflow has been wired
  to the environment, and nothing here can guarantee that came first. Writing
  into an environment that does not exist is a 404, so ONCE creates it."
  [opts {:keys [github private-file]}]
  (let [env (env-name opts)
        base ["--repo" github "--env" env]]
    [{:label (format "%s environment %s" github env)
      :args ["gh" "api" "--method" "PUT" "--silent"
             (format "repos/%s/environments/%s" github env)]}
     {:label (format "%s SERVER_IP" github)
      :args (concat ["gh" "variable" "set" "SERVER_IP"] base
                    ["--body" (str (:ip opts))])}
     {:label (format "%s SERVER_USER" github)
      :args (concat ["gh" "variable" "set" "SERVER_USER"] base
                    ["--body" "deploy"])}
     {:label (format "%s SSH_KNOWN_HOSTS" github)
      :args (concat ["gh" "variable" "set" "SSH_KNOWN_HOSTS"] base
                    ["--body" (str (:once/known-hosts opts))])}
     {:label (format "%s SSH_PRIVATE_KEY" github)
      :args ["sh" "-c"
             (str "gh secret set SSH_PRIVATE_KEY --repo " (shell-quote github)
                  " --env " (shell-quote env)
                  " < " (shell-quote private-file))]}]))

(defn revoke-commands
  "The gh invocations that withdraw one repository's credentials. Delete needs
  no key material, so this works with the box already destroyed — which is why
  it runs before teardown rather than after."
  [opts {:keys [github]}]
  (let [env (env-name opts)
        base ["--repo" github "--env" env]]
    [{:label (format "%s SERVER_IP" github)
      :args (concat ["gh" "variable" "delete" "SERVER_IP"] base)}
     {:label (format "%s SERVER_USER" github)
      :args (concat ["gh" "variable" "delete" "SERVER_USER"] base)}
     {:label (format "%s SSH_KNOWN_HOSTS" github)
      :args (concat ["gh" "variable" "delete" "SSH_KNOWN_HOSTS"] base)}
     {:label (format "%s SSH_PRIVATE_KEY" github)
      :args (concat ["gh" "secret" "delete" "SSH_PRIVATE_KEY"] base)}]))

(defn commands
  "Every gh invocation this run makes, in order."
  [opts]
  (let [delete? (= :delete (:green/event opts))
        entries (if delete?
                  ;; Groups, not applications: a repository named twice was
                  ;; revoked twice before, issuing the same four calls again.
                  (validate/deploy-groups opts)
                  (or (:once/deploy-keys opts) []))]
    (vec (mapcat #((if delete? revoke-commands publish-commands) opts %) entries))))

;;; ------------------------------------------------------------------ the step

(defn- token-env
  [opts]
  {"GH_TOKEN" (str (:github-token opts))})

(defn- cleanup!
  [opts]
  (when-let [dir (:once/key-dir opts)]
    (remove-key-directory! dir))
  (-> opts
      (dissoc :once/key-dir)
      (update :once/deploy-keys #(mapv (fn [k] (dissoc k :private-file)) (or % [])))))

(defn github-step
  "Publish on create, revoke on delete, do nothing otherwise.

  `wire-fn` runs the same branch for `:build` and `:create`, so the event check
  here is what keeps a build from reaching GitHub; `side-effecting-steps` only
  covers `--dry-run`.

  A revoke that fails because there is nothing to revoke is not an error:
  delete has to be re-runnable, and a missing secret is the state it is trying
  to reach."
  ([opts] (github-step opts process/run-with-timeout))
  ([opts run-fn]
   (let [event (:green/event opts)
         delete? (= :delete event)]
     (if-not (contains? #{:create :delete} event)
       opts
       (let [opts (cond-> opts
                    (and (not delete?) (seq (validate/deploy-groups opts)))
                    (assoc :once/known-hosts (fetch-host-key opts run-fn)))
             result (process/run-plan
                     (commands opts)
                     {:runner (fn [{:keys [args]}]
                                (run-fn (vec args) {:extra-env (token-env opts)} run-timeout-ms))
                      :continue? (fn [_ _] delete?)})
             opts (cleanup! opts)]
         (if (zero? (:exit result))
           (assoc opts :green/exit 0)
           (assoc opts :green/exit 1
                  :green/err (format "gh failed for %s: %s"
                                     (get-in result [:command :label])
                                     (str/trim (str (:err result)))))))))))
