#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["package-once-blue", "blue", "colors-compute-blue"]
#
# [tool.uv.sources]
# package-once-blue = { git = "https://github.com/getcolors/once.git", rev = "6374d37e29b54330f30d675f8aa65e47542f1008", subdirectory = "blue" }
# blue = { git = "https://github.com/getcolors/blue.git", rev = "784018bb586882efbd91affd42139582a40ea1d1" }
# colors-compute-blue = { git = "https://github.com/getcolors/colors-compute.git", rev = "9ecd0749e9632732f6226d5b73267dcab60c2e09", subdirectory = "blue" }
# ///
"""Thin launcher for package-once-blue."""
from package_once_blue import exec, run

__all__ = ["run"]

if __name__ == "__main__":
    exec()
